language: php
php:
- '5.5'
- '5.4'
- '5.3'
deploy:
  provider: heroku
  strategy: git
  app: nsu-gold
  api_key:
    secure: CPNQMdBqaDntehxIpVFPWcR5Ei0O2l0cpv7lLhWvaAdkRhL54uUK/T87sAhb4f2361n7vtD1XH2BRpooPVFJIBphYumP0iPEza0Z1MYwYFLs10Cuh87buOndnqbJdBC58xctoHTTUudCIh8CwOxPNIXCsT035f2E9xobAL38KjE=
