<div class="panel panel-default">
    <div class="panel-heading">Sign In</div>
    <div class="panel-body">
        <form class="form-horizontal" action="/login/submit" method="post">
            <div class="form-group">
                <label for="username" class="col-sm-2 control-label">Username</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="username" placeholder="Username">
                </div>
            </div>
            <div class="form-group">
                <label for="password" class="col-sm-2 control-label">Password</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="password" placeholder="Password">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <div class="checkbox">
                        <label>
                            <input disabled type="checkbox">Remember me
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">Sign in</button>
                </div>
            </div>
        </form>
    </div>
    <div class="panel-footer">
        <a href="<?php echo $this->url('register'); ?>">Don't have an account?</a>
        <a href="<?php echo $this->url('forgot-password'); ?>">Forgot password?</a>
    </div>
</div>