<head>
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,300,700')
        ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css')
        ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css')
    ?>
</head>

<body>

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>Sign In!</h3>
        </div>
        <div class="panel-body">
            <form action="/login/post" method="post" name="sign_in_form">
                <div class="header">
                    <p><strong>Roomie!</strong></p>
                </div>
                <div class="form-group">
                    <input type="text" class="button" id="username" name="username" placeholder="Username">
                </div>
                <div class="form-group">
                    <input type="password" class="button" id="password" name="password" placeholder="Password"><br>
                </div>
                <div class="form-group">
                    <input type="submit" class="button" id="submit" value="SIGN IN"><br>
                </div>
                <div class="form-group">
                    <a href="<?php echo $this->url('forgot-password'); ?>">Forgot password?</a>
                    &nbsp;
                    <a href="<?php echo $this->url('register'); ?>">Don't have an account?</a>
                </div>
            </form>
        </div>
        <div class="panel-footer">
        </div>
    </div>
</div>

<?php
/*
<form action="/login/post" method="post" name="sign_in_form">
    <div class="header">
        <p><strong>Roomie!</strong></p>
    </div>
    <div style="margin-right: 11em;">Sign in to continue</div>
    <div>
        <input type="text" class="button" id="username" name="username" placeholder="Username"><br>
        <input type="password" class="button" id="password" name="password" placeholder="Password"><br>
        <input type="submit" class="button" id="submit" value="SIGN IN"><br>
    </div>
    <div class="optional">
        <a href="<?php echo $this->url('forgot-password'); ?>">Forgot password?</a>
        <span id="space"></span>
        <!--input type="checkbox" id="remember" name="remember">
          <label for="remember"><span></span>Remember me</label-->
    </div>
    <div class="footer">
        <p><span><a href="<?php echo $this->url('register'); ?>">Register</a></span></p>
    </div>
</form>
*/
?>

</body>