
<div class="container">

    <div class="panel panel-default">
        <div class="panel-heading"><h3>Expense Calculator</h3></div>
        <div class="panel-body">
            <div class="form-group" id="add-item-group">

                <div class="col-sm-4 col-xs-4">
                    <input type="text" class="form-control" id="item-add" placeholder="Amount spent">
                </div>
                <div class="col-sm-4 col-xs-4">
                    <input type="text" class="form-control" id="item-add" placeholder="Roomie price">
                </div>
                <div class="col-sm-2 col-xs-2">
                    <button type="button" id="btn-add-item" class="btn btn-primary" data-loading-text="Adding..." autocomplete="off">Calculate</button>
                </div>
                <div class="col-sm-2 col-xs-2">
                    <button type="button" id="btn-add-item" class="btn btn-primary" data-loading-text="Adding..." autocomplete="off">Upload</button>
                </div>
            </div>
            <div class="col-sm-4 col-xs-4" style="margin-top: 10px;">
                <ul class="list-group">
                    <li class="list-group-item">
                        <input type="checkbox" aria-label="...">
                        justo odio</li>
                    <li class="list-group-item">
                        <input type="checkbox" aria-label="...">
                        Dapibus ac facilisis in</li>
                    <li class="list-group-item">
                        <input type="checkbox" aria-label="...">
                        Morbi leo risus</li>
                    <li class="list-group-item">
                        <input type="checkbox" aria-label="...">
                        Porta ac consectetur ac</li>
                    <li class="list-group-item">
                        <input type="checkbox" aria-label="...">
                        Vestibulum at eros</li>
                </ul>
            </div>
        </div>

        <div class="panel-footer">
            <button type="submit" class="btn btn-default" id="btn-delete">Send Mail</button>
        </div>
    </div>
</div>
    <!--script>
        $('#btn-delete').on('click', function () {
            $('input:checkbox').each(function () {
                var sThisVal = (this.checked ? $(this).attr('id') : "");
                if (sThisVal != "") {
                    $.ajax({
                        url: "/shopping-list/delete",
                        data: {
                            id: sThisVal
                        }
                    }).done(function (response) {
                        $('#' + response.data.id).parent().parent().remove();
                    });
                }
            });

        });

        $('#btn-add-item').on('click', function () {
            var $btn = $(this).button('loading');
            $.ajax({
                url: "/shopping-list/add",
                data: {
                    item: $('#item-add').val(),
                    username: 'Aaron'
                }
            }).done(function(response) {
                var divCheck = $('<div></div>').addClass('checkbox');
                var labelCheck = $('<label></label>');
                var inputCheck = $('<input type="checkbox" />');

                labelCheck.append(inputCheck);
                labelCheck.append(response.data.item);
                divCheck.append(labelCheck);
                $('#add-item-group').before(divCheck);

                $('#item-add').val('');
                $btn.button('reset');
            });
        });
    </script-->
