<?php $this->headLink()->prependStylesheet('/css/upload.css') ?>
<div class="container">

    <div class="panel panel-default">
        <div class="panel-heading"><h3>Expense Calculator</h3></div>
        <div class="panel-body">
            <div class="form-group" id="add-item-group">

                <div class="col-sm-4 col-xs-4">
                    <input type="text" class="form-control" id="spent" placeholder="Amount spent">
                </div>
                <div class="col-xs-2-4 col-xs-2">
                    <input type="text" class="form-control" id="split" placeholder="Roomie price">
                </div>
                <div class="col-x-2-2 col-xs-2">
                    <button type="button" id="btn-add-item" class="btn btn-primary" onclick="myfunction()" data-loading-text="Adding..." autocomplete="off">Calculate</button>
                </div>
				<div class="row">    
       <div class="col-sm-4 col-xs-2">  
            <!-- image-preview-filename input [CUT FROM HERE]-->
            <div class="input-group image-preview">
                <input type="text" class="form-control image-preview-filename" disabled="disabled"> <!-- don't give a name === doesn't send on POST/GET -->
                <span class="input-group-btn">
                    <!-- image-preview-clear button -->
                    <button type="button" class="btn btn-default image-preview-clear" style="display:none;">
                        <span class="glyphicon glyphicon-remove"></span> Clear
                    </button>
                    <!-- image-preview-input -->
                    <div class="btn btn-default image-preview-input">
                        <span class="glyphicon glyphicon-folder-open"></span>
                        <span class="image-preview-input-title">Browse</span>
                        <input type="file" accept="image/png, image/jpeg, image/gif" name="input-file-preview"/> <!-- rename it -->
                    </div>
                </span>
            </div><!-- /input-group image-preview [TO HERE]--> 
        </div>
            </div>
</div>
            <!--<div class="col-sm-4 col-xs-4" style="margin-top: 10px;">
                <ul class="list-group">
                    <li class="list-group-item">
                        <input type="checkbox" aria-label="...">
                        justo odio</li>
                    <li class="list-group-item">
                        <input type="checkbox" aria-label="...">
                        Dapibus ac facilisis in</li>
                    <li class="list-group-item">
                        <input type="checkbox" aria-label="...">
                        Morbi leo risus</li>
                    <li class="list-group-item">
                        <input type="checkbox" aria-label="...">
                        Porta ac consectetur ac</li>
                    <li class="list-group-item">
                        <input type="checkbox" aria-label="...">
                        Vestibulum at eros</li>
                </ul>
            </div>*/-->
            <div class="col-sm-4 col-xs-4" style="margin-top: 10px;">
            <ul class="list-group">
            <?php foreach($this->listCollection as $member): ?>
                <li class="list-group-item">
                        <input type="checkbox" class="" id="<?php echo $member->getEmail(); ?>" />
                        <?php echo $member->getEmail(); ?>
                </li>
            <?php endforeach; ?>
            </ul>
            </div>
        </div>

        <div class="panel-footer">
            <button type="submit" class="btn btn-default" id="btn-delete">Send Mail</button>
        </div>
    </div>
</div>

<script type="text/javascript">
$(document).on('click', '#close-preview', function(){ 
    $('.image-preview').popover('hide');
    // Hover befor close the preview
    $('.image-preview').hover(
        function () {
           $('.image-preview').popover('show');
        }, 
         function () {
           $('.image-preview').popover('hide');
        }
    );    
});

$(function() {
    // Create the close button
    var closebtn = $('<button/>', {
        type:"button",
        text: 'x',
        id: 'close-preview',
        style: 'font-size: initial;'
    });
    closebtn.attr("class","close pull-right");
    // Set the popover default content
    $('.image-preview').popover({
        trigger:'manual',
        html:true,
        title: "<strong>Preview</strong>"+$(closebtn)[0].outerHTML,
        content: "There's no image",
        placement:'bottom'
    });
    // Clear event
    $('.image-preview-clear').click(function(){
        $('.image-preview').attr("data-content","").popover('hide');
        $('.image-preview-filename').val("");
        $('.image-preview-clear').hide();
        $('.image-preview-input input:file').val("");
        $(".image-preview-input-title").text("Browse"); 
    }); 
    // Create the preview image
    $(".image-preview-input input:file").change(function (){     
        var img = $('<img/>', {
            id: 'dynamic',
            width:250,
            height:200
        });      
        var file = this.files[0];
		
        var reader = new FileReader();
        // Set preview image into the popover data-content
        reader.onload = function (e) {
            $(".image-preview-input-title").text("Change");
            $(".image-preview-clear").show();
            $(".image-preview-filename").val(file.name);            
            img.attr('src', e.target.result);
            $(".image-preview").attr("data-content",$(img)[0].outerHTML).popover("show");
        }        
        reader.readAsDataURL(file);
    });  
});

function myfunction()
{
var first = document.getElementById("spent").value;
var userList = document.querySelectorAll('input[type="checkbox"]:checked').length;
var answer = parseFloat(first)/parseFloat(userList);
var ans = answer;
split.value=ans;
}
</script>

