<form action="#" method="post" name="sign_in_form">
    <div class="header">
        <p><strong>Roomie!</strong></p>
    </div>
    <div style="margin-right: 11em;">Sing in to continue</div>
    <div>
        <input type="text" class="button" id="username" name="username" placeholder="Username"><br>
        <input type="password" class="button" id="password" name="password" placeholder="Password"><br>
        <input type="submit" class="button" id="submit" value="SIGN IN"><br>
    </div>
    <div class="optional">
        <a href="<?php echo $this->url('forgot-password'); ?>">Forgot password?</a>
        <span id="space"></span>
        <!--input type="checkbox" id="remember" name="remember">
          <label for="remember"><span></span>Remember me</label-->
    </div>
    <div class="footer">
        <p><span><a href="<?php echo $this->url('register'); ?>">Register</a></span></p>
    </div>
</form>