<div class="row-fluid">
    <!--<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">-->
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="row">
                <div class="col-sm-10">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                            <img src="<?php //echo $this->basePath('img/zf2-logo.png') ?>" alt="Roomie!"/>
                            &nbsp;<?php //echo $this->translate('Roomie!') ?>
                        </a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                            <li class=""><a href="<?php echo $this->url('shopping-list') ?>"><?php echo $this->translate('Shopping') ?></a></li>
                            <li class=""><a href="<?php echo $this->url('expenses') ?>"><?php echo $this->translate('Expenses') ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
                <div class="col-sm-2">
                    <a href="<?php echo $this->url('login'); ?>" class="navbar-link">Sign In</a>
                    &nbsp;
                    <a href="<?php echo $this->url('register'); ?>" class="navbar-link">Register</a>
                </div>
            </div>
        </div>
    </nav>
</div>