<div class="panel panel-default">
    <div class="panel-heading"><h3>Users</h3></div>
    	<div class="panel-body">
        	<div class="checkbox">
            	<label>
                	<input type="checkbox" class="" id="<?php echo $User->getId();?>"/>
                   <?php echo $User->getItem();?>
               </label>
               <div>
             <?php endforeach;?>
          	  <div class="form-group" id="add-user-group">
             		<div class="col-sm-8 col-xs-6">
                    <input type="text" class="form-control" id="user-add" placeholder="Add Roomies">
                    </div>
                    <div class="col-sm-4 col-xs-6">
                    	<button type="button" id="btn-add-user" class="btn btn-primary" data-loading-text="Adding..." autocomplete="off">Add</button>
                        </div>
                  </div>
             </div>
       <div class="panel-footer">
          <button type="submit" class="btn btn-default" id="btn-delete">Delete</button>
      </div>
</div>
<script>
	$('#btn-delete').on('click',function(){
		$('input:checkbox.each(function(){
			var sThisVal=(this.checked ? $(this).attr('id') : "");
				if(sthisVal != ""){
					$ajax({
						url: "<?php echo $this->url('user-list');?>/delete",
						data:{
							id: sThisVal
						}
					}).done(function (response){
						$('#' + response.data.id).parent().parent().remove();
					});
				}
		});
	});
	
	$('#btn-add-user').on('click',function(){
			
		});
					