<form>
    <!-- title -->
    <div class="header">
        <p><strong>Shopping List</strong></p>
    </div>
    <!-- these are the 10 textboxes to submit code -->
    <div>
        <?php echo $this->username; ?>

        <?php foreach($this->shoppinglist as $item): ?>
            <input type="text" class="button" id="item" name="item1" placeholder="<?= $item ?>" value="" ><br>

        <?php endforeach; ?>

    </div>
    <!-- buttons -->
    <div>
        <input type="submit" class="button2" id="submit" value="Add">
        <input type="submit" class="button2" id="submit" value="Delete">
        <input type="submit" class="button2" id="submit" value="Pay">

    </div>
</form>