<form>
    <!-- title -->
    <div class="header">
        <p><strong>Shopping List</strong></p>
    </div>
    <!-- these are the 10 textboxes to submit code -->
    <div>
        <?php echo $this->username ?>
    
        
        <input type="text" class="button" id="item" name="item1" placeholder="Enter item" value="" ><br>
        <input type="text" class="button" id="item" name="item2" placeholder="Enter item"><br>
        <input type="text" class="button" id="item" name="item3" placeholder="Enter item"><br>
        <input type="text" class="button" id="item" name="item4" placeholder="Enter item"><br>
        <input type="text" class="button" id="item" name="item5" placeholder="Enter item"><br>
        <input type="text" class="button" id="item" name="item6" placeholder="Enter item"><br>
        <input type="text" class="button" id="item" name="item7" placeholder="Enter item"><br>
        <input type="text" class="button" id="item" name="item8" placeholder="Enter item"><br>
        <input type="text" class="button" id="item" name="item9" placeholder="Enter item"><br>
        <input type="text" class="button" id="item" name="item" placeholder="Enter item"><br>
    </div>
    <!-- buttons -->
    <div>
        <input type="submit" class="button2" id="submit" value="Add">
        <input type="submit" class="button2" id="submit" value="Delete">
        <input type="submit" class="button2" id="submit" value="Pay">

    </div>
</form>