<form>
    <!-- title -->
    <div class="header">
        <p><strong>Shopping List</strong></p>
    </div>
    <!-- these are the textboxes to submit code -->
    <div>
        <?php echo $this->username; ?>

        <ul>
        <?php foreach($this->shoppinglist as $item): ?>
            <li><?= $item ?></li>
        <?php endforeach; ?>
        </ul>
        <input type="text" class="button" id="item" name="item1" placeholder="Placeholder" value="" ><br>

    </div>
    <!-- buttons -->
    <div>
        <input type="submit" class="button2" id="submit" value="Add">
        <input type="submit" class="button2" id="submit" value="Delete">
        <input type="submit" class="button2" id="submit" value="Pay">

    </div>
</form>