<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>Forgot Password?</h3>
        </div>
        <div class="panel-body">
            <form action="/forgot-password/post" method="post" name="forgot_password_form">
                <div class="header">
                    <p><strong>Roomie!</strong></p>
                </div>
                <div class="form-group">
                    <input type="text" class="button" id="username" name="username" placeholder="Username">
                </div>
                <div class="form-group">
                    <input type="submit" class="button" id="submit" value="Submit"><br>
                </div>
                <div class="form-group">
                    <a href="<?php echo $this->url('login'); ?>">Already have an account?</a>
                    &nbsp;
                    <a href="<?php echo $this->url('register'); ?>">Don't have an account?</a>
                </div>
            </form>
        </div>
        <div class="panel-footer">
        </div>
    </div>
</div>

<?php
/*
<div class="row-fluid panel panel-default">
    <div class="panel-heading">Forgot password</div>
    <div class="panel-body">
        <form class="form-horizontal" action="<?php echo $this->url('forgot-password'); ?>/submit" method="post">
            <div class="form-group">
                <label for="username" class="col-sm-2 control-label">Username</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="username" placeholder="Username">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>
            </div>
        </form>
    </div>
    <div class="panel-footer">
        <a href="<?php echo $this->url('login'); ?>">Already have an account?</a>
        <a href="<?php echo $this->url('register'); ?>">Don't have an account?</a>
    </div>
</div>
*/
?>