<div class="row-fluid panel panel-default">
    <div class="panel-heading">Forgot password</div>
    <div class="panel-body">
        <form class="form-horizontal" action="<?php echo $this->url('forgot-password'); ?>/submit" method="post">
            <div class="form-group">
                <label for="username" class="col-sm-2 control-label">Username</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="username" placeholder="Username">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>
            </div>
        </form>
    </div>
    <div class="panel-footer">
        <a href="<?php echo $this->url('login'); ?>">Already have an account?</a>
        <a href="<?php echo $this->url('register'); ?>">Don't have an account?</a>
    </div>
</div>