<form action="#" method="post" name="register_form">
    <div class="header">
        <p><strong>Sign up</strong></p>
    </div>
    <div>
        <input type="text" class="button" id="name" name="name" placeholder="First Last"><br>
        <input type="text" class="button" id="email" name="email" placeholder="johndoe@gmail.com"><br>
        <input type="text" class="button" id="regusername" name="regusername" placeholder="Username"><br>
        <input type="password" class="button" id="regpassword" name="regpassword" placeholder="Password"><br>
        <input type="text" class="button" id="confirmPass" name="confirmPass" placeholder="Confirm Password"><br>
        <input type="text" class="button" id="adminpass" name="adminpass" placeholder="Administrator Password"><br>
        <input type="submit" class="button" id="submit" value="Register"><br>
    </div>

    <div class="optional">
        <a href="<?php echo $this->url('login'); ?>">Cancel</a>
        <span id="space"></span>
    </div>
    <div class="footer">

    </div>
</form>