<html>
<head>
    <meta charset="utf-8">
    <title>Register Form</title>
    <link rel="stylesheet" href="style.css">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
</head>

<body>
<form action="#" method="post" name="register_form">
    <div class="header">
        <p><strong>Sign up</strong></p>
    </div>
    <div>
        <input type="text" class="button" id="name" name="name" placeholder="First Last"><br>
        <input type="text" class="button" id="email" name="email" placeholder="johndoe@gmail.com"><br>
        <input type="text" class="button" id="regusername" name="regusername" placeholder="Username"><br>
        <input type="password" class="button" id="regpassword" name="regpassword" placeholder="Password"><br>
        <input type="text" class="button" id="confirmPass" name="confirmPass" placeholder="Confirm Password"><br>
        <input type="text" class="button" id="adminpass" name="adminpass" placeholder="Administrator Password"><br>
        <input type="submit" class="button" id="submit" value="Register"><br>
    </div>

    <div class="optional">
        <a href="index.php">Cancel</a>
        <span id="space"></span>
    </div>
    <div class="footer">

    </div>
</form>
</body>

</html>